//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Practical_14
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        public int Id { get; set; }
        public string Name { get; set; }

        [Required]
        [Column(TypeName = "Date")]
        [Display(Name = "JoiningDate")]
        [DataType(DataType.Date, ErrorMessage = "Only Date is Required"), DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime DOB { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
